### ISSUE TITLE
Works only in PT

### ISSUE THREAD

**Issue by octavioamu** [leonardovff/tinderLike#1]
I'm not a Tinder user but I suppose this code will work only when the app is loaded in portugues. There isn't a better selector?
https://github.com/leonardovff/tinderLike/blob/6c725f05d75b6a00aa90f2f3b8a033f819e1d880/app.js#L4

**Comment by marcelodeandrade** [comment]
You're right. Attribute `aria-label` is variable acoording language. The like button has a class `recsGamepad__button--like` which is permanent even the language is changed, can use a selector for this class.

**Comment by leonardovff** [comment]
Yes, I believe that class `recsGamepad__button--like` is the correct to use.

**Comment by leonardovff** [comment]
The correction is present in the master.
