### ISSUE TITLE
Add keywords to filter automatically

### ISSUE THREAD

**Issue by marcelodeandrade** [leonardovff/tinderLike#2]
A previous list declared with some keywords to filter profile through the bio description.

**Comment by leonardovff** [comment]
@marcelodeandrade we need to create one flag to control the use of keywords.

**Comment by marcelodeandrade** [comment]
I'll take care of it, @leonardovff

**Comment by vmesel** [comment]
@marcelodeandrade I've made some improvements to the list on #8 but I dont think that all words are going to be good filters for everybody. We need to specify a way to make it easier to run looking for certain kinds of people there.

**Comment by leonardovff** [comment]
@marcelodeandrade is the idea dislike the people that have the keywords in their bio profile?

**Comment by marcelodeandrade** [comment]
@vmesel  the keywords it's a little personal, the same words does not work for everyone, of course. When you said "make it easier", what do you think? 

@leonardovff exactly! The keywords filters some profiles to dislike, for example: everyone whos like _signos_ haha

**Comment by leonardovff** [comment]
I understand now @marcelodeandrade 
First time, I believe that the filter is to like. Example:
Who has the keywords in bio profile, like. Who hasn't the keywords in bio profile, dislike.
