### ISSUE TITLE
script didn't work

### ISSUE THREAD

**Issue by andrevandal** [leonardovff/tinderLike#5]
I tried to run the script but it didn't work.
The script runs and logs on the console but it didn't like people.

**Comment by derevandal** [comment]
Error on `filter()`
```js
Uncaught ReferenceError: recsCardboard__cards is not defined
    at filter (<anonymous>:28:2)
    at <anonymous>:1:1
```

**Comment by e-dong** [comment]
What do you mean by "it didn't like people". What is your script is supposed to do?

**Comment by andrevandal** [comment]
I recorded my screen.
The first like works... the next I don't.
[2017-10-04 19-30-07.zip](https://github.com/leonardovff/tinderLike/files/1357555/2017-10-04.19-30-07.zip)

**Comment by leonardovff** [comment]
@derevandal look the update
