### ISSUE TITLE
Update Readme.md

### ISSUE THREAD

**Issue by MuhammadHasham23** [leonardovff/tinderLike#6]
Add Details of your project in Readme.md.
This shall include:

*Project Demonstration (using images or just plain text)

**Comment by RavinduHasithanjana** [comment]
Hi i will work on update your Readme.md with screen shots

**Comment by marcelodeandrade** [comment]
@RavinduHasithanjana any progress?

**Comment by leonardovff** [comment]
@RavinduHasithanjana ?

**Comment by MuhammadHasham23** [comment]
Please merge this if it was useful to you.
Regards.

**Comment by leonardovff** [comment]
closed in #9

**Comment by leonardovff** [comment]
@marcelodeandrade the issue request gif showing the script running

**Comment by leonardovff** [comment]
closed at #10

**Comment by marcelodeandrade** [comment]
@leonardovff the issue still open. Need something more?
